spring.application.name=local-rag

# Ollama connection
spring.ai.ollama.base-url=http://localhost:11434

# Chat model configuration
spring.ai.ollama.chat.model=llama3.2

# Embedding model configuration
spring.ai.ollama.embedding.model=nomic-embed-text

# ChromaDB connection
spring.ai.vectorstore.chroma.client.host=http://[::1]
spring.ai.vectorstore.chroma.client.port=8000

# Collection name (like a "table" in ChromaDB)
spring.ai.vectorstore.chroma.collection-name=dsa-knowledge

# Auto-create collection if it doesn't exist
spring.ai.vectorstore.chroma.initialize-schema=true


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

